  - name: Environment | SSH tweak
    shell: perl -pi -e 's/AcceptEnv LANG LC_\*/# AcceptEnv LANG LC_\*/g' '/etc/ssh/sshd_config'
    notify: reload ssh

  - name: Environment | Set git user configuration
    template:
      src: gitconfig.j2
      dest: "{{ home_dir }}/.gitconfig"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Environment | Set Bash configuration
    template:
      src: bashrc.j2
      dest: "{{ home_dir }}/.bashrc"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Environment | Set some Bash aliases
    template:
      src: bash_aliases.j2
      dest: "{{ home_dir }}/.bash_aliases"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0644

  - name: Environment | Set up vimrc
    template:
      src: vimrc.local.j2
      dest: /etc/vim/vimrc.local
      owner: root
      mode: 0644
    become: yes

  - name: Environment | Copy public ssh key from host to {{ user }}
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: "{{ home_dir }}/.ssh/id_rsa.pub"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0600
    when: ssh_key_from_host

  - name: Environment | Copy private ssh key from host to {{ user }}
    copy:
      src: ~/.ssh/id_rsa
      dest: "{{ home_dir }}/.ssh/id_rsa"
      owner: "{{ user }}"
      group: "{{ group }}"
      mode: 0600
    when: ssh_key_from_host

